### ISSUE TITLE
The Dropdown is hidden the second time the options are open

### ISSUE THREAD

**Issue by raphaelcarlosr** [silviomoreto/bootstrap-select#1049]
First dropdown open, all right!
![image](https://cloud.githubusercontent.com/assets/483708/7916152/676bdc68-0858-11e5-84d2-c600e8bbcad7.png)

But when close and reopen .. the dropdown is hidden:
![image](https://cloud.githubusercontent.com/assets/483708/7916177/8f0d3f64-0858-11e5-8402-387d29ba253a.png)

My solution was:
```css
.bootstrap-select.open .dropdown-menu.inner{ display:block;}
```
I hope this helps
