### ISSUE TITLE
Selector positioning

### ISSUE THREAD

**Issue by vinagrito** [silviomoreto/bootstrap-select#110]
I have some selectors that have the 'pull-right' class.After applying boostrap-select I saw that the class was there but no CSS was taking care of it. So what do you think of

``` css
.bootstrap-select.btn-group.pull-right {
    float: right;
}
```
