### ISSUE TITLE
Support Bootstrap 4

### ISSUE THREAD

**Issue by hubgit** [silviomoreto/bootstrap-select#1135]
Bootstrap 4 (currently alpha) has a simplified `.dropdown-menu .dropdown-item` syntax.

http://v4-alpha.getbootstrap.com/components/dropdowns/

There's also no longer a requirement for the markup to be `ul` + `li` elements, so the dropdown menu can be simply a `div.dropdown-menu` container with `a.dropdown-item` items inside.

**Comment by pruimmartin** [comment]
When will there be support for bootstrap 4?

**Comment by caseyjhol** [comment]
I will make Bootstrap 4 a priority after its first official release.

**Comment by cubitworx** [comment]
The fact that this library doesn't yet support bootstrap 4 forces me to use something else which is very disappointing because it is such a nice implementation.

**Comment by snolflake** [comment]
@cubitworx Indeed, deal breaker :cry:

**Comment by Arakis** [comment]
Yes, i needed bootstrap v4 support in several month ago, too. Here is a "very simple", just working patch:

bootstrap-select.js:
...
Line 283
-    style: 'btn-default',
+    style: 'btn-secondary',
...
Line 477:
-            (typeof classes !== 'undefined' ? ' class="' + classes + '"' : '') +
+            (typeof classes !== 'undefined' ? ' class="dropdown-item ' + classes + '"' : '') +
...
Line 699:
       divider.className = 'divider';
+	  a.className = 'dropdown-item';

My bootstrap-select source is from 15. dec 2015. source lines are not valid now, of course.

I vote for bootstrap v4 support too, because i have a huge need, too. But my patch seems to work for my needs, it's not tested in detail. I use a very small feature set of the plugin.

**Comment by caseyjhol** [comment]
Bootstrap 4 is still in alpha, meaning _anything_ can be changed at any time. It also means that nobody should be using it in a production environment. Once it moves to beta I'll take a closer look as to what's required to support it.

**Comment by jtesch** [comment]
For my application I use the filtered select/multiselect using bootstrap-select 1.12.1:

I got it working with v4 by adding the following css to my own custom css:

```
.bootstrap-select.show>.dropdown-menu>.dropdown-menu {
    display: block;
}

.bootstrap-select > .dropdown-menu > .dropdown-menu li.hidden{
    display:none;
}

.bootstrap-select > .dropdown-menu > .dropdown-menu li a{
    display: block;
    width: 100%;
    padding: 3px 1.5rem;
    clear: both;
    font-weight: 400;
    color: #292b2c;
    text-align: inherit;
    white-space: nowrap;
    background: 0 0;
    border: 0;
}
```

You may be able to get a temporary fix for your use case by simply adding your own css to your css file.
Like caseyjhol said, v4 is in alpha and shouldn't be used for production. Any changes to either bootstrap-select plugin or Bootstrap 4 framework can break any temporary fixes such as the one above.

**Comment by gtournie** [comment]
What would be great is to be able to tweak it without having to fork the project.
I mean if we could configure the template a little bit (changing the classes, the type of tags...), everybody could use it with any version of Bootstrap

**Comment by rodrigo-martins** [comment]
https://github.com/rodrigo-martins/bootstrap-select.git

Hi guys,

I made a small changes in dist/js and dist/css for my application and **it is working Okay.** I didn't check if it is working for full compatibility on bootstrap 4.

PS.: Fontawesome are requered for multselect 

-Inserted dropdown-item on <li> <a> elements
-Update all divider to dropdown-divider
-Removed dropdown-menu on <ul> elements
-Small changed of .css

Best regards

**Comment by grosser** [comment]
Using this ... @jtesch patch + fix for btn-default

```Css
/* https://github.com/silviomoreto/bootstrap-select/issues/1135 */
.dropdown-toggle.btn-default {
  color: #292b2c;
  background-color: #fff;
  border-color: #ccc;
}

.bootstrap-select.show>.dropdown-menu>.dropdown-menu {
  display: block;
}

.bootstrap-select > .dropdown-menu > .dropdown-menu li.hidden{
  display:none;
}

.bootstrap-select > .dropdown-menu > .dropdown-menu li a{
  display: block;
  width: 100%;
  padding: 3px 1.5rem;
  clear: both;
  font-weight: 400;
  color: #292b2c;
  text-align: inherit;
  white-space: nowrap;
  background: 0 0;
  border: 0;
}
```

<img width="213" alt="screen shot 2017-04-14 at 4 42 34 pm" src="https://cloud.githubusercontent.com/assets/11367/25058708/6300cff0-2131-11e7-965b-fdc059a0e665.png">

**Comment by infostreams** [comment]
I've submitted a new pull request here https://github.com/silviomoreto/bootstrap-select/pull/1748 that works with the Bootstrap4 alpha-6, which you can install [as follows](https://stackoverflow.com/questions/33181297/npm-install-from-github-pull-request).

**Comment by trusktr** [comment]
Hello Everyone, just replace your script tags with these to use @infostreams's version with Bootstrap v4-alpha6:

```html
  <!-- bootstrap-select -->
  <link rel="stylesheet" href="https://cdn.rawgit.com/infostreams/bootstrap-select/fd227d46de2afed300d97fd0962de80fa71afb3b/dist/css/bootstrap-select.min.css" />
  <script src="https://cdn.rawgit.com/infostreams/bootstrap-select/fd227d46de2afed300d97fd0962de80fa71afb3b/dist/js/bootstrap-select.min.js"></script>
```

**Comment by trusktr** [comment]
Works great!

**Comment by infostreams** [comment]
Hi all,

I don't think it's wise to link directly to the files in my pull request. Referencing them within a package.json is one thing, but referencing them in production code is quite another. What if I decide to delete the pull request once (if ever) it gets merged? That your site then breaks is not on me :-)

Cheers,
Ed

**Comment by trusktr** [comment]
True. Download the files asap and host in your own project

**Comment by treaves** [comment]
I'm trying to install with the info from the link info streams provided, but, it does not seem to work.

yarn add silviomoreto/bootstrap-select#1748/head
zsh: no matches found: silviomoreto/bootstrap-select#1748/head

**Comment by gtournie** [comment]
FYI bootstrap 4 is in beta: https://getbootstrap.com/

**Comment by trusktr** [comment]
@treaves I don't think `#1748/head` is a valid ref? I think the format is `yarn add silviomoreto/bootstrap-select#<ref>` where `<ref>` is replaced with a commit hash, branch name, or tag name. At least that is the syntax with `npm` and I think `yarn` is probably similar.

**Comment by treaves** [comment]
Well, I was following the yarn docs.  Regardless, even without the '/head', I still get 'no matches found: silviomoreto/bootstrap-select#1748'

**Comment by trusktr** [comment]
Hello @treaves, 1748 is not a commit that exists. Look at the pull request's commits tab and use an existing commit number.

**Comment by trusktr** [comment]
@treaves did you get it?

**Comment by ghiscoding** [comment]
I took @grosser styling and found a few differences compare to released version of Bootstrap-Select. So I played with the styling a bit and came out with a near identical look as the original (see below). Also note that I replaced the Glyphicon checkmark with Font-Awesome icon (using content and unicode value).

Here's the CSS I used (similar to @grosser with a few variances, changed `width: auto`, font-awesome check icon, added hover color)
```css
/*
Make bootstrap-select work with bootstrap 4 see:
https://github.com/silviomoreto/bootstrap-select/issues/1135
*/
.dropdown-toggle.btn-default {
  color: #292b2c;
  background-color: #fff;
  border-color: #ccc;
}
.bootstrap-select.show > .dropdown-menu > .dropdown-menu,
.bootstrap-select > .dropdown-menu > .dropdown-menu li.hidden {
  display: block;
}
.bootstrap-select > .dropdown-menu > .dropdown-menu li a {
  display: block;
  width: 100%;
  padding: 3px 1.5rem;
  clear: both;
  font-weight: 400;
  color: #292b2c;
  text-align: inherit;
  white-space: nowrap;
  background: 0 0;
  border: 0;
  text-decoration: none;
}
.bootstrap-select > .dropdown-menu > .dropdown-menu li a:hover {
  background-color: #f4f4f4;
}
.bootstrap-select > .dropdown-toggle {
  width: auto;
}
.dropdown-menu > li.active > a {
  color: #fff !important;
  background-color: #337ab7 !important;
}
.bootstrap-select .check-mark {
  line-height: 14px;
}
.bootstrap-select .check-mark::after {
  font-family: "FontAwesome";
  content: "\f00c";
}
.bootstrap-select button {
  overflow: hidden;
  text-overflow: ellipsis;
}

/* Make filled out selects be the same size as empty selects */
.bootstrap-select.btn-group .dropdown-toggle .filter-option {
  display: inline !important;
}
```
#### Sample with extra styling and Font-Awesome icon

![select1](https://user-images.githubusercontent.com/643976/30779694-4034d386-a0c5-11e7-9da6-f67ed3c27329.jpg)



#### Sample with `badge` instead of `label`

![select3](https://user-images.githubusercontent.com/643976/30779683-0599eaf4-a0c5-11e7-807d-5ec0ec64c892.jpg)




#### Multi-select with optgroups

![select2](https://user-images.githubusercontent.com/643976/30779650-20c05d28-a0c4-11e7-8083-7ba27e678856.jpg)

**Comment by pete-woods** [comment]
@ghiscoding Total noob at modern grunt / javascript / css packaging here. What file in the bootstrap-select source tree to I overwrite / append to with your .css there? I tried replacing the contents of "less/bootstrap-select.less", but that didn't seem to work after building and running the test.html (with bootstrap 4 included instead).

**Comment by pete-woods** [comment]
Ah, just realised the idea is you put that in your app's CSS. D'oh! Looks like it nearly works apart from the 'hidden' class having been removed from bootstrap 4. I guess that means the Javascript needs tweaking too.

> The .hidden and .show classes have been removed because they conflicted with jQuery’s $(...).hide() and $(...).show() methods. Instead, try toggling the [hidden] attribute, use inline styles like style="display: none;" and style="display: block;", or toggle the .invisible class.

**Comment by pete-woods** [comment]
Well. FWIW, here's yet another tweaked CSS. This fixes the visibility of elements when searching. I think maybe it was a simple typo in the @ghiscoding 's CSS.

```
/*
Make bootstrap-select work with bootstrap 4 see:
https://github.com/silviomoreto/bootstrap-select/issues/1135
*/
.dropdown-toggle.btn-default {
  color: #292b2c;
  background-color: #fff;
  border-color: #ccc;
}
.bootstrap-select.show > .dropdown-menu > .dropdown-menu {
  display: block;
}
.bootstrap-select > .dropdown-menu > .dropdown-menu li.hidden {
  display: none;
}
.bootstrap-select > .dropdown-menu > .dropdown-menu li a {
  display: block;
  width: 100%;
  padding: 3px 1.5rem;
  clear: both;
  font-weight: 400;
  color: #292b2c;
  text-align: inherit;
  white-space: nowrap;
  background: 0 0;
  border: 0;
  text-decoration: none;
}
.bootstrap-select > .dropdown-menu > .dropdown-menu li a:hover {
  background-color: #f4f4f4;
}
.bootstrap-select > .dropdown-toggle {
  width: 100%;
}
.dropdown-menu > li.active > a {
  color: #fff !important;
  background-color: #337ab7 !important;
}
.bootstrap-select .check-mark {
  line-height: 14px;
}
.bootstrap-select .check-mark::after {
  font-family: "FontAwesome";
  content: "\f00c";
}
.bootstrap-select button {
  overflow: hidden;
  text-overflow: ellipsis;
}

/* Make filled out selects be the same size as empty selects */
.bootstrap-select.btn-group .dropdown-toggle .filter-option {
  display: inline !important;
}
```

**Comment by joshuaswilcox** [comment]
None of these patch seem to be working for me, clicking the dropdown doesn't remove the `    display: none;` from `.dropdown-menu`

**Comment by ckosmowski** [comment]
:+1:

**Comment by reimax** [comment]
Bootstrap-select v1.12.2
Bootstrap v4.0.0-beta.2
fix style pete-woods.

after click on select i get error:
```
Uncaught TypeError: Cannot read property 'jquery' of undefined
    at new t (frontend.min.js:5)
    at a.g.toggle (frontend.min.js:6)
    at HTMLButtonElement.<anonymous> (frontend.min.js:6)
    at Function.each (frontend.min.js:1)
    at he.fn.init.each (frontend.min.js:1)
    at he.fn.init.a._jQueryInterface [as dropdown] (frontend.min.js:6)
    at HTMLButtonElement.<anonymous> (frontend.min.js:6)
    at HTMLDocument.dispatch (frontend.min.js:2)
    at HTMLDocument.v.handle (frontend.min.js:2)
```
old version work correct in Bootstrap 3.x

Can anyone do a working example for b4?

**Comment by fatcrobat** [comment]
We created a working shim repository with composer support at https://github.com/heimrichhannot/bootstrap-select if you already need bootstrap 4 support. The markup fits the new bootstrap-4 dropdown requirements.

**Comment by karagenit** [comment]
@fatcrobat I wrapped up your fork into a Gem to make it a bit easier to use with Rails here:

https://github.com/karagenit/bootstrap-select-rails

That way you only have to depend on the `bootstrap4-select-rails` gem instead of messing with npm/bower.

**Comment by fatcrobat** [comment]
@karagenit Feel free. ;)

**Comment by renhammington** [comment]
Bootstrap Select is part of my essential kit, and I can't work without it! Testament to it's awesomeness...  we're in beta for Bootstrap 4 now, so is there any progress on even a beta implementation of bootstrap-select with support for BS4? If there's a way we can contribute... what do you need?

**Comment by caseyjhol** [comment]
Sorry - I've been swamped with another project lately. I've almost got it ready to go, and I'm hopeful it could be available this week.

**Comment by mehran9** [comment]
yes please @caseyjhol , thanks for your awesome contributions.

**Comment by doaa-altarawy** [comment]
How can it work with Bootsrap 4 !

**Comment by ghiscoding** [comment]
@doaa-altarawy I suggest you to read the entire post. You'll most probably find the answer to your question

**Comment by doaa-altarawy** [comment]
Sorry, maybe I wasn't clear. When will the support for Bootstrap 4 be pushed?

**Comment by tomalakgeretkal** [comment]
In theory now's the time to do it, with two Bootstrap v4 betas already released.
Unfortunately there were breaking changes between the two betas, so it's clearly not actually at beta-level stability. If I were the author of this plugin, frankly I'd wait until v4 gets real.

**Comment by krahamath** [comment]
How long it will take to release or any estimate date to release with support bootstrap 4 ?

**Comment by michaelzangl** [comment]
This is how I solved it (using SCSS):

```css
.bootstrap-select {
  .dropdown-toggle {
    @extend .btn-secondary;
    .pull-left {
      float: none;
    }
  }

  .dropdown-menu.inner {
    display: block;

    > li > a {
      @extend .dropdown-item;
    }
  }
}
```
