### ISSUE TITLE
doesnt play well with pjax

### ISSUE THREAD

**Issue by ctf0** [silviomoreto/bootstrap-select#1407]
basicly the lib doesnt get the chance to construct its dom structure & 
```css
select.selectpicker {
    display: none!important;
}
```
doesn't get disabled, so the original select stays hidden.
