### ISSUE TITLE
wrong width on select-block-level

### ISSUE THREAD

**Issue by d1rk** [silviomoreto/bootstrap-select#173]
Because of that css rule:

``` css
.bootstrap-select:not([class*="span"]) {
width: 220px;
}
```

the width gets overwritten and does not behave as expected. Could you please update that rule and/or remove it?

Thanks for your effort. You did a good job.
