### ISSUE TITLE
Width bootstrap select for bootstrap 3.0

### ISSUE THREAD

**Issue by GesJeremie** [silviomoreto/bootstrap-select#461]
``` css
.bootstrap-select:not([class*="span"]):not([class*="col-"]):not([class*="form-control"]) {
width: 220px;
}
```

replace 220px by 100% to fit with col-md-6, etc.
