### ISSUE TITLE
bootstrap-select doesn't support RTL

### ISSUE THREAD

**Issue by SamerX** [silviomoreto/bootstrap-select#862]
When using bootstrap-select with RTL websites it should render from right to left, RTL mainly is done using <body dir='rtl'>, bootstrap select doesn't support RTL

**Comment by mewsoft** [comment]
I am having the same issue with RTL I am using Bootstrap RTL support from here

https://github.com/morteza/bootstrap-rtl

The problem only with the button and cart, the text is always left and the cart right.

The problem I guess with this css:

```
.bootstrap-select.btn-group .btn .filter-option {
    display: inline-block;
    overflow: hidden;
    width: 100%;
    text-align: left; /* in RTL text-align: right; will fix it */
}
and for the cart, this css:
.bootstrap-select.btn-group .btn .caret {
    position: absolute;
    top: 50%;
    right: 12px;  /* left: 12px; will fix it*/
    margin-top: -2px;
    vertical-align: middle;
}
```
I think you should restrict for using pull left and pull right classes of bootstarp.

Note for using bootstrap-rtl, the author refused to convert the pull-left and pull-right classes so you have to implement these yourself.
Just append these css classes to the end of bootstrap-rtl.css:

```
.pull-right {
	float: left !important;
}
.pull-left {
	float: right !important;
}
.text-right {
	text-align: left;
}
.text-left {
	text-align: right;
}
```

The fork with this modifications here:

https://github.com/mewsoft/bootstrap-rtl

**Comment by margani** [comment]
Thanks so much for this great answer.
For caret it's better this way:
.bootstrap-select.btn-group .btn .caret {
	position: absolute;
	top: 50%;
	left: 12px;
	right:auto; /* this line should be added to override the default behavior */
	margin-top: -2px;
	vertical-align: middle;
}

**Comment by margani** [comment]
Also for better style this should be added:
```css
.bootstrap-select > .dropdown-toggle {
	padding-left: 25px;
	padding-right: 15px;
}
```

**Comment by ahmedam55** [comment]
thanks for the comment @margani

**Comment by surenderpicnframes** [comment]
Thanks  margani  its really works

**Comment by yasharvc** [comment]
Hi, Try setting text-align:right in .filter-option class...

**Comment by mutazharara** [comment]
`.bootstrap-select.btn-group .dropdown-toggle .filter-option {
    text-align: right;
}
.bootstrap-select>.dropdown-toggle {
    padding-left: 25px;
    padding-right: 12px;
}
.bootstrap-select.btn-group .dropdown-toggle .caret {
    right: auto;
    left: 12px;
}
.bootstrap-select.btn-group .dropdown-menu li a{
     text-align: right;
}`

**Comment by kmuharam** [comment]
This worked for me:

```
.bootstrap-select.btn-group .btn .filter-option {
    display: inline-block !important;
    overflow: hidden !important;
    width: 100% !important;
    text-align: right !important; 
}

.bootstrap-select.btn-group .dropdown-toggle .filter-option {
    float: right;
}
```

**Comment by Farshadi73** [comment]
If you have problem with dropdown-toggle direction, try this, work for me
```
.dropdown-toggle::after {
  float: left;
  margin-top: 0.6em;
  vertical-align: 0.1em;
}
```

**Comment by iyadthayyil** [comment]
This worked for me with bootstrap 4 and https://github.com/morteza/bootstrap-rtl
`.dropdown-toggle::after {
    float: left;
    margin-top: 0.6em;
    vertical-align: 0.1em;
}
.bootstrap-select .dropdown-toggle .filter-option {
    text-align: right!important;
}
.bootstrap-select .dropdown-toggle .filter-option-inner {
    padding-right: 0!important;
}`

**Comment by iyadthayyil** [comment]
This worked for me with Bootstrap 4 and https://github.com/morteza/bootstrap-rtl
```css
/*Bootstrap select RTL fix*/
.dropdown-toggle::after {
    float: left;
    margin-top: 0.6em;
    vertical-align: 0.1em;
}
.bootstrap-select .dropdown-toggle .filter-option {
    text-align: right!important;
}
.bootstrap-select .dropdown-toggle .filter-option-inner {
    padding-right: 0!important;
}
```
